serviceAccount:
  name: kube-bench
  roleArn: "arn:aws:iam::165220828225:role/eks-cluster-role-20251104045833076200000002"  # IAM role

image:
  repository: "aquasec/kube-bench"
  tag: "v0.6.10"                                  
  pullPolicy: IfNotPresent

aws:
  accountId: "165220828225"
  region: "us-east-1"
  clusterArn: "arn:aws:eks:us-east-1:165220828225:cluster/my-eks-cluster"  # EKS cluster ARN

benchmark: "eks-1.2.0"

job:
  name: kube-bench
